name:                distprog
version:             0.1.0.0
github:              "githubuser/distprog"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/distprog#readme>

dependencies:
- base >= 4.7 && < 5
- template-haskell
- time
- exceptions
- bytestring
- containers
- data-accessor
- stm
- binary
- deepseq
- distributed-static
- network-transport
- network-transport-tcp
- mtl
- hashable
- rank1dynamic
- random
- syb

library:
  source-dirs: src

executables:
  hello-exe:
    main:                Main.hs
    source-dirs:         app/helloworld
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - distprog

  twoproc-exe:
    main:                Main.hs
    source-dirs:         app/twoprocesses
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - distprog

  remoteproc-exe:
    main:                Main.hs
    source-dirs:         app/spawnremoteprocess
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - distprog

tests:
  distprog-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - distprog
